### ISSUE TITLE
Remove audio.js from source tree

### ISSUE THREAD

**Issue by xrotwang** [clld/clld#115]
Since the HTML5 `audio` element is now [widely supported](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility), we should remove audio.js from the source tree.

Also from the [LICENSE](https://github.com/clld/clld/blob/master/LICENSE.txt#L24-L25).

**Comment by tutfakulunto** [comment]
I was hoping to work on this, but when I searched the files after cloning the project, the only reference to "audio.js" I found was in LICENSE.txt.

**Comment by xrotwang** [comment]
Well, it's still there: https://github.com/clld/clld/tree/master/clld/web/static/audiojs
