### ISSUE TITLE
Maps: Labels vanish when mouse moves away even for “show labels”

### ISSUE THREAD

**Issue by Anaphory** [clld/clld#128]
If the mouse cursor moves away from a map label, that label is hidden – even when all labels were shown using “show/hide labels” or creating a map type that shows labels.

**Comment by xrotwang** [comment]
Yes, that's somewhat annoying. I'm reluctant, though, to go down the rabbit hole of getting the interaction between leaflet default behaviour and clld functionality to show/hide labels completely correct. I think the current state is at least somewhat transparent for the user: Selecting "show" will display all labels, de-selecting "show" will hide all - no matter what their previous state was. In between, it's plain leaflet.
