### ISSUE TITLE
Find a way to track git commit ID's and tags in webapps

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/clld#134]
Find a way to show git(hub) commit ID's and tags (V1 etc) of the data repositories in their respective webapps. This will help reproducibility and make the data served by a webapp more transparent.

**Comment by xrotwang** [comment]
It is simple to discover and display the git commit hash for the code serving the app. To track the same information for the data repository, the commit hash would have to be imported into the database upon DB initialization - which is an app-specific process, thus would have to be dealt with per app.

What could be done in clld is provide a template tag which reads and displays a known key from the `Config` table.
