### ISSUE TITLE
xlwt-future breaks compatibility with Python 3.6.x

### ISSUE THREAD

**Issue by chrzyki** [clld/clld#137]
Using xlwt-future with Python 3.6.x causes a `ValueError: cannot use LOCALE flag with a str pattern`. The fix is easy: use xlwt instead of xlwt-future (tested with 3.6.3). However, I can't fathom how this affects backwards compatibility.

**Comment by xflr6** [comment]
Fixed in https://github.com/clld/clld/commit/d3148a7a2dd08cce9e538b1a668e1bb84def72cb (development branch)
