### ISSUE TITLE
Store and display version info for data repository

### ISSUE THREAD

**Issue by xrotwang** [clld/clld#141]
For apps which serve data curated in a separate data repository (e.g. Glottolog), it would be good to have shared functionality to
- store this info upon db initialization
- display this info in the web app

Note: This supersedes #134

**Comment by xflr6** [comment]
Nice, TIL about `git describe` (06bb3d2729a4cc7930a6eb11ea3be8613c4ae516): Do we want to add the `--tags` flag here?

https://github.com/clld/clldutils/blob/6597c4bda6aaa7d56b187a2eb540679168e33987/src/clldutils/path.py#L208

E.g. in `glottolog`:

```sh
$ git describe --always
pyglottolog-1.0.0-308-ge2a7331cf9
$ git describe --always --tags
v3.1.1-99-ge2a7331cf9
```
(The former ignores lightweight git tags, which where used in that repo)

**Comment by xrotwang** [comment]
Yes, good idea!

**Comment by xflr6** [comment]
Done: https://github.com/clld/clldutils/commit/30e43be34e3f5aad3c913c097e7db1ba6bc5a349

**Comment by xrotwang** [comment]
Not much of an issue anymore, now that we move towards apps serving released, versioned CLDF datasets.
