### ISSUE TITLE
Added words are not shownig

### ISSUE THREAD

**Issue by oopcode** [clld/clld#176]
The following code is copy-pasted from [documentation](https://clld.readthedocs.io/en/latest/initializedb.html) and placed inside `<myapp>/scripts/initializedb.py`:

```python
    data = Data()

    dataset = common.Dataset(id=starling.__name__, domain='starling.clld.org')
    DBSession.add(dataset)

    # All ValueSets must be related to a contribution:
    contrib = common.Contribution(id='contrib', name='the contribution')

    # All ValueSets must be related to a Language:
    data.add(common.Language, 'eng', id='eng', name='English', latitude=52.0, longitude=0.0)

    # We model words as units of a language:
    unit = common.Unit(id='unit', name='hand', language=data['Language']['eng'])

    # Part of speech is a typical parameter which can be "measured" for words or lexemes.
    pos = common.UnitParameter(id='pos', name='part of speech')

    DBSession.add(common.UnitValue(id='unit-pos', name='noun', unit=unit, unitparameter=pos, contribution=contrib))
```

However, after running `python <myapp>/scripts/initializedb.py development.ini` and navigating to application web interface I get English as the language **but** no words saved for this language. The data I added, however, is present in database's `unit` and `unitvalue` tables.

If I try to save language-level parameters (copy-pasted from the same [documentation](https://clld.readthedocs.io/en/latest/initializedb.html#language-level-parameters-and-values)), the parameters end up visible in the interface.

I use PostgreSQL and `pip`-installed `clld`.

 What am I doing wrong? Sorry if this is not the place to ask such questions.

**Comment by xrotwang** [comment]
In case you are still having this issue: If the database is populated, then you did everything right :)
By default, `Unit`s are not displayed by the app, but navigating to `http://localhost:6543/units` should show them. To display a language's `Unit`s on the language details page, you'd have to pull in the units table. This can be done by putting code like
```
${request.get_datatable('units', h.models.Unit, language=ctx).render()}
```
into a custom `language/detail_html.mako` template.
