### ISSUE TITLE
getting started troubles

### ISSUE THREAD

**Issue by SamPassmore** [clld/clld#179]
Hi, 

I am trying to run through the getting started walkthrough here:
https://clld.readthedocs.io/en/latest/tutorial.html

In the bootstrapping section I get to this line:
pip install -r requirements.txt

However, I do not have a file requirements.txt in this directory. 

```
pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

Is there a step missing? Or is there some implicit knowledge that I don't have? 

Thanks.

**Comment by xrotwang** [comment]
Sorry, I guess this is a documentation bug. Running "pip install -e ."
should do the trick.
Will double-check on Monday.

SamPassmore <notifications@github.com> schrieb am Sa., 9. März 2019, 11:17:

**Comment by xrotwang** [comment]
@SamPassmore does this work for you? Closing now, but feel free to re-open or open new issue if you run into more problems.

**Comment by SamPassmore** [comment]
Yup. Perfect 👌 thanks!
