### ISSUE TITLE
Release CLLD 4.5.0

### ISSUE THREAD

**Issue by chrzyki** [clld/clld#182]
- [x] fix failing doc builds
- [x] release `clld 4.5.0`, following https://github.com/clld/clld/blob/master/RELEASING.md

**Comment by chrzyki** [comment]
Fixing the failing doc build probably needs an update to the webhooks (due to GitHub deprecating the old webhooks). Do you have an account with readthedocs to get the integration URL for a new webhook, @xrotwang?

**Comment by xrotwang** [comment]
I guess I had one :)

**Comment by xrotwang** [comment]
ok, just added the webhook. Next push should cause a doc rebuild.

**Comment by chrzyki** [comment]
Perfect, thanks!

**Comment by chrzyki** [comment]
Webhook seems to be working, but the docs are still failing:

https://readthedocs.org/projects/clld/builds/8747702/

This could either be due to something like [this](https://github.com/bigdatagenomics/adam/issues/1917) or incorrect `virtualenv` settings in the readthedocs admin area or a need to specify an older sphinx version. Not quite sure yet what is causing this. :)

**Comment by xrotwang** [comment]
ok, switching to build with py3 seems to have fixed this.

**Comment by chrzyki** [comment]
Perfect, thanks!

**Comment by chrzyki** [comment]
https://github.com/clld/clld/releases/tag/v4.5.0
