### ISSUE TITLE
While trying to add rows to a *_data table the column name `key` clashes with the named parameter 'key' of function clld.scripts.util.Data.add()

### ISSUE THREAD

**Issue by Bibiko** [clld/clld#194]
https://github.com/clld/clld/blob/1f7c30dc77d266df2dc06dc3c8032d5961703297/src/clld/scripts/util.py#L351

If one tries to store a data row in a *_data table the following error message occurs:
`TypeError: add() got multiple values for argument 'key'`
due to the fact that ****kw** [see ⬇︎]
https://github.com/clld/clld/blob/1f7c30dc77d266df2dc06dc3c8032d5961703297/src/clld/db/models/_mixins.py#L117
**and** the function by itself clld.scripts.util.Data.add(self, model, **key**, **kw) contain the named parameter `key`.

If one changes the named parameter `key` into, let's say, `keyword` in clld.scripts.util.Data.add() then storing the data works like a charm.

**Comment by xrotwang** [comment]
Renaming to `key_` would be my preference here, since the trailing `_` is a common convention to avoid name clashes.

**Comment by xrotwang** [comment]
@Bibiko but typically, you wouldn't use `Data.add` to insert `*_data` instances into the DB, but rather `DBSession.add` directly. `Data.add` is only useful when you want to lookup objects lateron in the import process, but for `*_data` instances that's typically not needed.

**Comment by Bibiko** [comment]
ok - I see - but I'd go for changing the named parameter names into:
`def add(self, model_, key_, **kw):`
to allow column names `model` and `key` if there'll be a situation where one wants to add data via `Data.add()`.

**Comment by Bibiko** [comment]
I've tried to only use DBSession.add() to insert data having a column named `key` and it does not work:
File ".../site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
TypeError: add() got an unexpected keyword argument 'key'

**Comment by xrotwang** [comment]
`DBSession.add` is just SQLAlchemy's [`add`](https://docs.sqlalchemy.org/en/13/orm/session_api.html#sqlalchemy.orm.session.Session.add) method, so it expects an instance of the model class, i.e. `model(**kw)`, as argument.

**Comment by Bibiko** [comment]
ah - yes, of course - sorry for the confusion - thus we can leave it as it is?

**Comment by xrotwang** [comment]
I'd leave the issue open and fix it with the next clld release. But cutting a clld release just for this issue now seems unnecessary.

**Comment by Bibiko** [comment]
👍
