### ISSUE TITLE
Defaulting to object's string conversion may introduce weird behaviour

### ISSUE THREAD

**Issue by Anaphory** [clld/clld#197]
Falling back to `str(obj)` in 
https://github.com/clld/clld/blob/388dc367ce56f90fab3fb1bded865513d2d2bac1/src/clld/web/util/helpers.py#L323

leads to unexpected behaviour when the name of the object contains `<&>`. Because the label can be specified explicitly for other cases, I would assume it is safe to take the `html.encode()` of the object's name; the alternative is to always be more verbose.

**Comment by xrotwang** [comment]
What exactly is the uexpected behaviour? As far as I can tell, by virtue of using the `HTML` class, the content is encoded appropriately:
```
>>> from clld.web.util.htmllib import HTML
>>> print(HTML.a('<&>'))
<a>&lt;&amp;&gt;</a>
>>> print(HTML.a('<&>', title='<&>'))
<a title="&lt;&amp;&gt;">&lt;&amp;&gt;</a>
```

**Comment by xrotwang** [comment]
Or do you see any double encoding?

**Comment by Anaphory** [comment]
No, quite the opposite: The comment for the form ‘rope’ in https://lexirumah.model-ling.eu/lexirumah/languages/mamb1306-NWbar contains `<t>`, which you can see being escaped in https://lexirumah.model-ling.eu/lexirumah/values/66086. So it's the interplay of this column and the `datatables.Col` class, which does not apply escaping, so I end up with a `<t>` tag instead of `&lt;&gt;`.

**Comment by xrotwang** [comment]
@Anaphory is this still an issue or can we close this?
