### ISSUE TITLE
Rename in zope.sqlalchemy breaks clld

### ISSUE THREAD

**Issue by Anaphory** [clld/clld#198]
The [`ZopeTransactionExtension` class was renamed to `ZopeTransactionEvents`](https://pypi.org/project/zope.sqlalchemy/#id1), which breaks

https://github.com/clld/clld/blob/388dc367ce56f90fab3fb1bded865513d2d2bac1/src/clld/db/meta.py#L17

There should be two possible ways to fix it:
1. We could wrap it in a `try`/`except ImportError` block (ugly)
2. Use the `register()` function, which I believe is explained a few code blocks down in https://github.com/zopefoundation/zope.sqlalchemy/tree/master/src/zope/sqlalchemy#example

**Comment by xrotwang** [comment]
Using `register(DBSession)` instead of the `extension=` keyword seems to work - although I have to admit that I'm not entirely sure how to test this. Will roll out a fix and deploy for an app to see this in production.

**Comment by xrotwang** [comment]
@Anaphory WALS runs on clld 5.0.1 now, see https://github.com/shh-dlce/appconfig/commit/b82b488714c8e0e97790c49c59b3fca71f3b67c6
Looks ok so far.
