### ISSUE TITLE
Creating CLLD applications from CLDF datasets

### ISSUE THREAD

**Issue by LinguList** [clld/clld#205]
A template would be very useful, as it helps, especially when working on a new larger cldf dataset, to show the "customers" the potential final product already during orthography profile creation etc.

And if we could consecutively expand this template, e.g., by adding phoneme inventories per language (with IPA charts), this would even render everything more powerful (but that is something that would probably come with practice).

Example datasets (currently private) are:

1. without cognates: the Linguistic Survey of India at lexibank/lsi
2. in rudimentary state, in the end with cognates and alignments: lexibank/tppsr
3. the lexcauc database by Belyaev: https://github.com/lexcauc/lexcauc-db

The latter is still in the stage of development, so most interesting for now would be the LSI, where we already added custom methods to show the data a bit more interactively (with colored sounds, etc.).

**Comment by xrotwang** [comment]
Ok, so for the case of LSI, we would have to kinds of parameters: Concepts and Phonemes, right? Where phonemes are computed from the segmented data?

**Comment by LinguList** [comment]
Yes, one could say so, I guess.

**Comment by xrotwang** [comment]
Since the `pcreate` command (installed with `pyramid`) is deprecated (and consequently clld app templates will stop working), I'll start this as [cookiecutter template](https://cookiecutter.readthedocs.io/en/latest/index.html).

**Comment by xrotwang** [comment]
Actually, I'll use this opportunity to move the current templates to being cookiecutter based, and add a `clld` sub-command `create` which [calls cookiecutter](https://cookiecutter.readthedocs.io/en/latest/advanced/calling_from_python.html).

**Comment by xrotwang** [comment]
See also #206

**Comment by LinguList** [comment]
Okay, so with CLLD, i'd then call `clld create myproject`?

**Comment by xrotwang** [comment]
yes. The functionality is unreleased so far, i.e. you'd need HEAD from `clld/clld`.

**Comment by xrotwang** [comment]
closed in favor of more specific #209
