### ISSUE TITLE
CLDF bib must be read with lowercase flag

### ISSUE THREAD

**Issue by xrotwang** [clld/clld#212]
When importing the CLDF bib in
https://github.com/clld/clld/blob/03e465c00bfddf1ac3e363d9db2e44609debc116/src/clld/project_template/%7B%7Bcookiecutter.directory_name%7D%7D/%7B%7Bcookiecutter.directory_name%7D%7D/scripts/initializedb.py#L68
a `lowercase=True` keyword argument must be passed to make sure `bibtex2obj` works.

**Comment by marctang** [comment]
Thanks! Just to be sure that I get it: which part of sources.bib should be in lower case? Should I make the change from the initial sources.bib file in ` cldf-datasets/tangclassifiers/raw`?

**Comment by xrotwang** [comment]
@marctang you only have to change the call `bibtex.Database.from_file(args.cldf.bibpath)` in your `scripts/initializedb.py` to
```python
bibtex.Database.from_file(args.cldf.bibpath, lowercase=True)
```
and then re-run `clld initdb`. No change of the data is needed (and non-lowercase BibTeX field names are allowed per BibTeX spec).

**Comment by marctang** [comment]
Aaaah sorry I misunderstood the content! I changed it accordingly and everything works fine now! You are the best :-D! Thank you so much!
