### ISSUE TITLE
Support for multiple datasets in args.cldf for initializedb

### ISSUE THREAD

**Issue by chrzyki** [clld/clld#216]
I think it would be neat to have support for a list of datasets that can be supplied for `initializedb` with `--cldf` (and subsequently returning a list of the loaded datasets) here:

https://github.com/clld/clld/blob/a9ff5739f0040b3d50c9174a414712196184d3ab/src/clld/commands/initdb.py#L52-L53

Or is there another way to do this?

**Comment by xrotwang** [comment]
Nope, Good call. In particular because we already have code somewhere that
detects multiple metadata files in a directory.

Christoph Rzymski <notifications@github.com> schrieb am Fr., 31. Juli 2020,
18:43:

**Comment by xrotwang** [comment]
I'd propose we allow passing a directory as `--cldf` and then detect datasets via `pycldf.iter_datasets`. For backwards compatibility, `args.cldf` would still be a single `pycldf.Dataset` if a filename was passed, but a `list` otherwise.
