### ISSUE TITLE
No matching distribution found error for yuicompressor==2.4.8

### ISSUE THREAD

**Issue by esbesb** [clld/clld#230]

**Comment by xrotwang** [comment]
That problem was fixed here: https://github.com/clld/clld/commit/d92e688792bca52304c6c1b7f72951b89fe8ed57 included in [clld 7.4.1](https://github.com/clld/clld/releases/tag/v7.4.1)

**Comment by esbesb** [comment]
Thank you so much for the quick response! 
I already built an app 2 years ago with previous version of clld and now I'm trying to reinstall it on different computer and it's giving me problem. What should I do in this case? Should I rebuild the app?

**Comment by esbesb** [comment]
I upgraded the clld version but it gives me an strange error when populating the data, which is
`ModuleNotFoundError: No module named 'clld.scripts'`.

**Comment by xrotwang** [comment]
`clld` gained a proper commad line interface (the `clld` command) recently. Now, the way to call the functions in `initializedb.py` is
```
clld initdb development.in
```
see https://clld.readthedocs.io/en/latest/tutorial.html#populating-the-database
and the functionality formerly available in `clld.scripts` has moved to [`clld.cliutil`](https://github.com/clld/clld/blob/master/src/clld/cliutil.py) - so you may have to adapt the imports in `initializedb.py`.

**Comment by esbesb** [comment]
Oh that's great! Thanks!

I was using `clld.script.initializedb` function to populate the database with the data files like 
```
python myapp/scripts/initializedb.py development.ini --module myapp language_data.tsv parameter_data.tsv form_data.tsv sources_data.bib 
```
But it seems like `clld.script.initializedb` has removed and doesn't exist in `clld.cliutil` anymore. And I couldn't find the replacement of it either. Is there any other function that works similarly? Or can you please tell me what I can do instead?

**Comment by xrotwang** [comment]
What `clld.scripts.util.initializedb` did was basically calling two functions provided by an app - each in a separate transaction (see https://github.com/clld/clld/blob/355598f68e3a22fe00d6926cc9ded8834c4673fd/src/clld/scripts/util.py#L237-L248). That's now done when you run `clld initdb`, see https://github.com/clld/clld/blob/fddf76d481d76a4b34530e2b18021a222a965127/src/clld/commands/initdb.py#L68-L74

It seems that you passed some additional arguments before. That's not possible with the `clld initdb` command. But you could prompt the user for this input (using `input`) within your `main` or `prime_cache` function.

May I see your `myapp/scripts/initializedb.py`? This may help me understand better what the additional arguments do.

**Comment by esbesb** [comment]
Of course. Here is the `myapp/scripts/initializedb.py`
```
import collections
import csv

from clld.db.meta import DBSession
from clld.db.models import common
from clld.lib import bibtex
from clldutils.misc import slug
from clld.scripts.util import bibtex2source, initializedb, Data

from myapp.models import myappLanguage, myappSource
from myapp import models


data = Data()

class LanguageDataset:

    class LanguageDatasetDialect(csv.Dialect):
        delimiter = '\t'
        lineterminator = '\r\n'
        quoting = csv.QUOTE_NONE
        strict = True


    Language = collections.namedtuple('Language', [
        'name',
        'family',
        'latitude',
        'longitude',
        'region',
        'glottocode',
        'iso'])


    def __init__(self, dataset_fp):
        self.dataset_fp = dataset_fp


    def gen_languages(self):
        with open(self.dataset_fp, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f, dialect=self.LanguageDatasetDialect)
            for row in reader:
                yield self.Language(
                        row['name'],
                        row['family'],
                        row['latitude'],
                        row['longitude'],
                        row['region'],
                        row['glottocode'],
                        row['iso'])



def add_myapplanguages(lang_dataset, session):

    d = {}

    for lang in lang_dataset.gen_langs():
        d[lang.glottocode] = myappLanguage(
                id=lang.glottocode,
                name=lang.name,
                family=lang.family,
                latitude=lang.latitude,
                longitude=lang.longitude,
                region=lang.region,
                glottocode=lang.glottocode,
                iso639=lang.iso)

        session.add(d[lang.glottocode])

    session.flush()

    return d


def add_sources(sources_file_path, session):

    d = {}

    bibtex_db = bibtex.Database.from_file(sources_file_path, encoding='utf-8')

    for record in bibtex_db:
        [record.id] = bibtex2source(record)
        session.add(myappSource[record.id])
    DBSession.flush()

    return d



def main(args):

    add_meta_data(DBSession)

    for record in bibtex.Database.from_file(args.sources_data, encoding='utf-8'):
        data.add(myappSource, record.id, _obj=bibtex2source(record, cls=myappSource))

    myapplanguages = add_myapplanguages(LanguageDataset(args.language_data), DBSession)



def add_meta_data(session):

    dataset = common.Dataset(
        id='myapp',
        name='myapp',
        description='',
        contact='',
        domain='')
    session.add(dataset)

    dataset.editors.append(common.Editor(
        contributor=common.Contributor(id='author', name='Author')))



if __name__ == '__main__':
    language_data_arg = [('language_data',)]
    sources_data_arg = [('sources_data',)]

    initializedb(language_data_arg, sources_data_arg, create=main)
```

**Comment by xrotwang** [comment]
Ok, so with something like
```python
def main(args):
    add_meta_data(DBSession)

    for record in bibtex.Database.from_file(input('path to sources: '), encoding='utf-8'):
        data.add(myappSource, record.id, _obj=bibtex2source(record, cls=myappSource))

    myapplanguages = add_myapplanguages(LanguageDataset(input('path to language data: ')), DBSession)
```
you should be able to initialize the db via
```shell
clld initdb development.ini
```

**Comment by esbesb** [comment]
Sorry for being disappeared. It worked wonderfully. Thank you so much for your help!
