### ISSUE TITLE
`cookiecutter` must be installed manually for `clld create <app>` to run

### ISSUE THREAD

**Issue by lemontree210** [clld/clld#242]
When running `clld create <appname>`, the following error message is displayed:
```
cookiecutter must be installed to create project templates
```
Installing `cookiecutter` solves the problem. Maybe it could get installed automatically along with `clld`

I see that the necessity of installing `cookiecutter` is mentioned [here](https://github.com/cldf/cookbook/blob/master/recipes/clld/README.md#bootstrapping-a-clld-app), but not in [documentation](https://clld.readthedocs.io/en/latest/tutorial.html#bootstrapping-a-clld-app).

**Comment by xrotwang** [comment]
I updated the docs. One could turn `cookiecutter` into an [extra](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies), thus make it installable via `pip install clld[dev]` or similar. But I'm not sure that would be less confusing. Installing it by default is something I'd not be willing to do for a package that's primarily intended to be installed on servers, where the bootstrapping functionality is not needed and where I'd like to minimize the installed code.

**Comment by lemontree210** [comment]
I see. I'm not sure I understand, though:

> package that's primarily intended to be installed on servers, where the bootstrapping functionality is not needed 

I thought `cookiecutter` could be used whenever you just want to create the app quickly (the same idea is conveyed in [Pyramid docs](https://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/cookiecutters.html)). In case of `clld` it makes even more sense because I would imagine that a standard layout of a `clld` app will suit most database creators. Why should it make a difference where the package will be installed? 

Maybe it's a dumb question. Anyway, I see the rationale behind not including it in the default setup and so updating the docs makes sense.
