### ISSUE TITLE
Disable/remove download per table button

### ISSUE THREAD

**Issue by Bibiko** [clld/clld#244]
Should we remove the button entirely or should we add a parameter `show_download_btn` for

https://github.com/clld/clld/blob/5730967b853d1697ae6e1d5123af3ea843961489/src/clld/web/util/downloadwidget.py#L53

à la 

`def render(self, no_js=False, show_download_btn=False):`

for cases where a download button is desired?

**Comment by xrotwang** [comment]
Remove entirely (and also remove the corresponding download info section displayed by the info button).
