### ISSUE TITLE
Remove esri base layers

### ISSUE THREAD

**Issue by xrotwang** [clld/clld#249]
See https://www.esri.com/arcgis-blog/products/developers/developers/open-source-developers-time-to-upgrade-to-the-new-arcgis-basemap-layer-service/

**Comment by thejourneyler** [comment]
Is this so much about "remove" or switch APIs? It seems from the linked
article it is about switching the APIs.

**Comment by xrotwang** [comment]
Switching APIs **and** registering for an API key.
