### ISSUE TITLE
HTML conversion in source URL generates the wrong string

### ISSUE THREAD

**Issue by davidainman** [clld/clld#260]
We have a source in our database with the following (super minimal repro) bib entry:

```
@misc{languageprojectyurok,
	title        = {Yurok Language Project Digital Archive},
	url          = {https://linguistics.berkeley.edu/~yurok/index.php}
}

```
When the URL is rendered, e.g. on sources/languageprojectyurok the ~ is turned into %C2%A0 rather than %7E, which makes the link not work:

[https://linguistics.berkeley.edu/ yurok/index.php](https://linguistics.berkeley.edu/%C2%A0yurok/index.php)

**Comment by davidainman** [comment]
Just checked: Yes, it is already corrupted in the DB.

**Comment by xrotwang** [comment]
Ok, can confirm. `bibtex2source` seems to be the culprit:
```python
>>> from clld.lib.bibtex import Database
>>> db = Database.from_file('../cldf/sources.bib')
>>> rec = db['yuroklanguageprojectonline']
>>> '~' in rec['url']
True
>>> from clld.cliutil import Data, slug, bibtex2source
>>> bibtex2source(rec).url
'https://linguistics.berkeley.edu/\xa0yurok/web/search.php'
```
