### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by mitselek** [clld/clld#49]
You might consider semantic versioning http://semver.org.

**Comment by xrotwang** [comment]
@mitselek While I'm aware of semantic versioning, the main reason for our somewhat idiosyncratic versioning scheme is that we have not heard of any other users of `clld` so far - so we act under the assumption that the only things we might break are our own apps. I guess as soon as this changes, we'd aim for a 1.0.0 release and try to stick to semantic versioning.

**Comment by xrotwang** [comment]
We will try to adopt semantic versioning with one deviation: We may also increment the PATCH number only, when adding functionality which is only needed in one or two of our apps in a backwards-compatible way.
The rationale behind this is as follows: We want to run all of our apps in reasonably similar environments, where reasonably similar means, using `clld` of the same MINOR version.

**Comment by mitselek** [comment]
Big thanks for letting me know.
We are working on introducing best practices of semver for language
community and Your input is highly appreciated.

Mihkel,
http://keeleressursid.ee/en/
