### ISSUE TITLE
Add CharisSil unicode fonts to clld:web/static

### ISSUE THREAD

**Issue by xrotwang** [clld/clld#50]
These fonts are useful for creating PDF documents containing unicode text, which is done in the `csd` and `tsammalex` apps already.

**Comment by bambooforest** [comment]
Doulos is also good.

**Comment by xrotwang** [comment]
Good or even better? Any preference?

**Comment by bambooforest** [comment]
Old version doesn't have italic, bold or bold italic. (Charis does.) I'm
loading the newest version of the fonts now and will let you know if that's
changed.
