### ISSUE TITLE
Put `not null` constraint on `ValuesetReference.source_pk`

### ISSUE THREAD

**Issue by xrotwang** [clld/clld#88]
In several places it is assumed that `ValuesetReference` instance's `source` attribute is not `None`. This assumption should be asserted by the data model.

**Comment by xflr6** [comment]
[Here](https://github.com/clld/glottolog3/blob/master/migrations/pending/fix_clld_assoc_tables.py) you find my unfinished stab at adding missing NOT NULL and UNIQUE

**Comment by xrotwang** [comment]
closed in #136
