### ISSUE TITLE
The documentation on how to populate the data base is very sparse.

### ISSUE THREAD

**Issue by Anaphory** [clld/clld#97]
http://clld.readthedocs.io/en/latest/tutorial.html#populating-the-database describes what feels like the second step in many of populating a clld-based database:

It describes how to create objects in `data`,
>     data.add(common.Language, 'mylangid', id='1', name='French')
>     data.add(common.Unit, 'myunitid', id='1', language=data['Language']['mylangid'])

and then follows this up with a disclaimer, saying
> Using data.add for all objects may not be a good idea for big datasets, because keeping references to all objects prevents garbage collection and will blow up the memory used for the import process.

Presumably, the basic way to generate database entries (the first step in my mental understanding) is to flatly generate the corresponding objects, with the following code corresponding to the generation above.

    mylang = common.Language('mylangid', id='1', name='French')
    common.Unit('myunitid', id='1', language=mylang)

Before talking about the dataset, or in a separate documentation entry because it would be helpful to see the reasoning behind it, it would be nice to give a minimal example of a data set (one data point for one language) that would show how parameters, languages, value sets and values interact.

**Comment by xrotwang** [comment]
Yeah, it's a bit of a chicken-egg problem: no users - bad docs :)
I may link to a couple of examples of other clld apps, though. Thanks for
the notification!
Am 06.06.2016 17:25 schrieb "Gereon Kaiping" <notifications@github.com>:

**Comment by Anaphory** [comment]
There are quite a few links to clld apps on the clld website, and googling for initializedb.py leads to a lot of hits eg. on github.

But none of them are very transparent for me, I'm missing the basic framework for what's needed to add some entries – I have now got as far as generating some pseudo-parameters, but all of them link to `None`. I have managed to create a test language that is shown in the language list, but it links to `None`, as well, and my systematic languages are not created at all.

In some cases, I get an error that the UNIQUE constraint is validated when flushing the database, where the software apparently wants to construct two datasets of the same name, which is not permitted.

Things like that.

A clean, minimal working example (for just one language with one parameter with one value) would be much more helpful than a pointer to several example clld apps, each with their own special cases.

**Comment by xrotwang** [comment]
Ok. Will do today.
Am 06.06.2016 23:41 schrieb "Gereon Kaiping" <notifications@github.com>:

**Comment by xrotwang** [comment]
So pretty minimal would be the following:
```python
def main(args):
    data = Data()

    dataset = common.Dataset(id=myapp.__name__, domain='myapp.clld.org')
    DBSession.add(dataset)

    # All ValueSets must be related to a contribution:
    contrib = common.Contribution(id='contrib', name='the contribution')

    # All ValueSets must be related to a Language:
    lang = common.Language(
        id='lang',
        name='A Language',
        latitude=20,
        longitude=20)

    param = common.Parameter(id='param', name='Feature 1')

    # ValueSets group Values related to the same Language, Contribution and 
    # Parameter
    vs = common.ValueSet(id='vs', language=lang, parameter=param, contribution=contrib)

    # Values store the actual "measurements":
    DBSession.add(common.Value(id='v1', name='value 1', valueset=vs))
    DBSession.add(common.Value(id='v2', name='value 2', valueset=vs))

```

**Comment by xrotwang** [comment]
I'll flesh this out a bot more, until there's one instance of all the model classes involved.

**Comment by Anaphory** [comment]
That example is a very helpful starting point, thank you!

**Comment by xrotwang** [comment]
I added more docs https://github.com/clld/clld/blob/master/docs/initializedb.rst
It doesn't show up on readthedocs yet, but should at some point.
