### ISSUE TITLE
How do I control visualization?

### ISSUE THREAD

**Issue by Anaphory** [clld/clld#98]
Thanks to @xrotwang for fixing my issues with starting how to setup a clld and fill it with data.

I now have a web server running and displaying values by language or by parameter, but I am at a loss finding out how to improve the visualization, and the documentation is not very helpful.

1. My languages are spread over a range of about 300 km, which makes the default zoom level inconvenient. Now the documentation states that `max_zoom` is among the “recognized `clld.web.maps.Map.options`”, but I don't know where to access and set that option. (Not that I think you meant to imply that `clld.web.maps.Map.options` is an object anyway?)
2. Anything on the maps is displayed just as orange circles. Somewhere, the app is aware that those circles correspond to two different domain elements with names “Y” and “N” (which should have the numerical values `1` and `0`, but I haven't tested that yet) – or something else for some parameters – because I can filter the map, sort, etc., but I can't find hints in the doc how to change the color or shape. Judging from some example apps, I had assumed I could maybe just pass a `color` value to some relevant `jsondata` attribute, but that's not the case.

**Comment by xrotwang** [comment]
ad 1) you can find an example how to customize parameter maps in the [APiCS app](https://github.com/clld/apics/blob/master/apics/maps.py#L57-L63). The custom map class [must be registered](https://github.com/clld/apics/blob/master/apics/maps.py#L100).

**Comment by xrotwang** [comment]
ad 2) map markers can be customized by registering a [custom IMapMarker implementation](https://github.com/clld/apics/blob/master/apics/__init__.py#L82-L99). Again, registration has to [happen explicitly](https://github.com/clld/apics/blob/master/apics/__init__.py#L124).

The `__call__` method of the `IMapMarker` implementation must return a full URL to an marker icon (which can be determined depending on the properties of the `ValueSet` for which the marker is going to be used).

Typically, you'd precompute the (relative) URLs of the icons upon population of the database per `DomainElement`, and store it in the `DomainElement`s `jsondata` dictionary.
