### ISSUE TITLE
`Unit…` example lacks a keyword argument

### ISSUE THREAD

**Issue by Anaphory** [clld/clld#99]
While wondering how to implement a lexicon with meaning classes and cognacy judgements in my clld, I reread the (now updated) [documentation of Unit values](http://clld.readthedocs.io/en/latest/initializedb.html#unit-level-parameters-and-values) and noticed that 

    DBSession.add(common.UnitValue(id='unit-pos', name='noun', unitparameter=pos, contribution=contrib))

seems to be missing the `unit=unit, ` keyword argument.

**Comment by xrotwang** [comment]
ah, true. will fix.
